name: Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build-and-publish"
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: basetool/basetool
      DOCKER_IMAGE_TAG: latest
      BASETOOL_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create .env file
        run: |
          echo "BASE_URL=localhost:7654\nNEXTAUTH_URL=http://localhost:7654\nDATABASE_URL=\n" > .env
          cat .env
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          cache-from: type=registry,ref=basetool/basetool:latest
          cache-to: type=inline

      - name: Install deps
        run: npm install yaml zx
      - name: Configure docker container
        run: |
          mv .env.sample .env
          ls -la .
          echo "DATABASE_URL=postgresql://basetool:basetool@database/basetool" >> .env
          echo "SECRET=123e48188c5e81703cf62bbb15d129a4329f5ec3c8fc2eda1493bb20448e8006" >> .env
          cat .env
        working-directory: ./deploy/docker
      - name: Update the compose file with new creds
        run: npx zx docker-setup.mjs
        working-directory: ./.github/workflows/docker-publish
      - name: Start docker container
        run: docker compose up --wait
        working-directory: ./deploy/docker
      - name: Sleep for 3s
        uses: juliangruber/sleep-action@v1
        with:
          time: 3s
      - name: Test app
        env:
          PORT: 7654
        run: npx zx ./.github/workflows/docker-publish/test-image.mjs

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
